### ISSUE TITLE
[Bug] Incorrect validation of password/PIN length

### ISSUE THREAD

**Issue by gptgit** [KwiatekMiki/passnpingenerator#14]
The program does not correctly validate the length of the password or PIN entered by the user. It allows lengths outside the specified range (4-100 for passwords and 4-10 for PINs) to be accepted without raising an error.

**Steps to Reproduce:**
1. Choose to generate a password or PIN.
2. Enter a length that is outside the specified range.
3. Observe the program's response.

**Expected Behavior:**
If the user enters a length that is outside the specified range, the program should raise a `ValueError` and display an error message.

**Actual Behavior:**
The program accepts lengths outside the specified range without raising an error, potentially leading to unexpected results.

**Additional Information:**
- Operating System: Windows 10
- Language: English
- Version: 1.0

**Comment by KwiatekMiki** [comment]
It works.

```> python main.py

█▀█ ▄▀█ █▀ █▀ █▄ █ █▀█ █ █▄ █
█▀▀ █▀█ ▄█ ▄█ █ ▀█ █▀▀ █ █ ▀█
       by KwiatekMiki

What do you want to generate? [P̲assword/Pi̲n/N̲ick]: p
How long password do you need? [4-100]: 1
Traceback (most recent call last):
  File "D:\Dane\Dokumenty\GitHub\passnpingenerator\main.py", line 57, in <module>
    checklen(length, 4, 100)
  File "D:\Dane\Dokumenty\GitHub\passnpingenerator\main.py", line 43, in checklen
    raise ValueError(trans["wronglength"])
ValueError: Wrong length.
```
