### ISSUE TITLE
[Suggestion] Simplify password and PIN generation logic

### ISSUE THREAD

**Issue by gptgit** [KwiatekMiki/passnpingenerator#17]
The current logic for generating passwords and PINs can be simplified and made more concise by utilizing Python's built-in functions and libraries.

**Implementation Details:**
1. Instead of using a loop to generate passwords and PINs character by character, utilize the `secrets.choice()` function to randomly select characters from the `chars` string.
2. Use the `secrets.token_urlsafe()` function to generate a secure random URL-safe string of the desired length for passwords. This function eliminates the need for the loop and ensures secure random generation.
3. Update the code to utilize the `secrets.token_hex()` function for generating PINs. This function generates a random hexadecimal string, which can be converted to a PIN by extracting the desired number of digits.
4. Remove the `strtoint()` and `checklen()` functions, as the built-in functions and libraries handle the length validation automatically.

**Expected Benefits:**
- Simplified and more concise code for password and PIN generation.
- Improved security by utilizing built-in functions for secure random generation.
- Elimination of custom length validation functions.

**Additional Context:**
By utilizing the built-in functions and libraries, the code for password and PIN generation can be simplified and made more secure. This approach also reduces the chance of introducing errors or vulnerabilities in custom implementation.

**Comment by KwiatekMiki** [comment]
1. 4c8f11e
2. what
3. I prefer to use `secrets.choice()`
4. what v2
