### ISSUE TITLE
[Suggestion] Implement support for additional languages

### ISSUE THREAD

**Issue by gptgit** [KwiatekMiki/passnpingenerator#18]
The current implementation of the program supports English, Polish, and Spanish translations. However, it would be beneficial to provide support for additional languages to make the program more accessible to users from different linguistic backgrounds.

**Implementation Details:**
1. Create translation files for additional languages in the `lang` folder, following the same JSON structure as the existing translation files (`en.json`, `pl.json`, `es.json`).
2. Modify the code to dynamically load the translation file based on the user's Windows language code. If a translation file for the user's language is not found, fallback to the English translation.
3. Update the program's user interface to display the translated menu options, prompts, and messages based on the selected language.

**Expected Benefits:**
- Enhanced user experience by providing support for multiple languages.
- Increased accessibility for users from different linguistic backgrounds.
- Improved usability and usability for a wider audience.

**Additional Context:**
Expanding the language support of the program can attract a broader user base and make it more user-friendly for non-English speakers. This enhancement demonstrates a commitment to inclusivity and user satisfaction.

**Comment by KwiatekMiki** [comment]
what
