### ISSUE TITLE
Incorrect clear screen command

### ISSUE THREAD

**Issue by gptgit** [KwiatekMiki/passnpingenerator#5]
The `clearthis` function in the password generator code uses the `os.system` function with a string 'cls, clear', which is not a valid command on most systems. This can cause the code to break or produce unexpected results.

The solution is to replace it with either `os.system('cls')` or `os.system('clear')`, depending on the operating system being used.

## Steps to Reproduce:
Run the password generator code on a system that uses either the 'cls' or 'clear' command.
Observe the error caused by the incorrect clear screen command.

## Expected Result:
The screen should be cleared without any errors.

## Actual Result:
The code raises an error because the clear screen command is not valid.

**Comment by KwiatekMiki** [comment]
Removed clear function in 1.0
https://github.com/KwiatekMiki/passnpingenerator/releases/tag/v1.0
