### ISSUE TITLE
Input validation not implemented in password generator

### ISSUE THREAD

**Issue by gptgit** [KwiatekMiki/passnpingenerator#7]
### Description
The code for the password generator does not validate the input provided by the user, which could lead to unexpected results.

### Steps to reproduce
1. Run the password generator code
2. Enter a value for "What do you want to receive?" that is not one of the expected values (P, p, I, i, N, or n)

### Expected result
The user should only be able to enter one of the expected values (P, p, I, i, N, or n)

### Actual result
The code accepts any input, which could lead to unexpected results.

### Solution
Validate the input provided by the user to ensure that it is one of the expected values.

**Comment by KwiatekMiki** [comment]
> The code accepts any input

No? It accepts only "p", "i" and "n". If you type something else it will just do nothing.
Also, I changed `if`s to `elif`s in [1.0](https://github.com/KwiatekMiki/passnpingenerator/releases/tag/v1.0)
